version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run compile
          name: Compile
      - run:
          command: npm run test
          name: Test
      - run:
          command: npm run bundle
          name: Bundle
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build:
    jobs:
      - build_and_test
      # - deploy:
      #     requires:
      #       - build_and_test # only deploy if the build_and_test job has completed
      #     filters:
      #       branches:
      #         only: main # only deploy when on main
